language: java

jdk:
  - openjdk11

addons:
  apt:
    update: true
  chrome: stable

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome

install: true

script:
- ./gradlew clean check --no-daemon --console=plain -i
- ./gradlew uitest --no-daemon --console=plain -i
